### ISSUE TITLE
Memory overloading issue

### ISSUE THREAD

**Issue by Anirudh257** [lshiwjx/2s-AGCN#12]
First of all, thanks a lot for making your code public. I am trying to do the experiment on NTU RGB D 120 dataset and I have split the data into training and testing in CS as given in the NTU-RGB D 120 paper. I have **63026** training samples and **54702** testing samples. I am trying to train the model on a GPU cluster but after running for one epoch, my model exceeds the memory limit:
![image](https://user-images.githubusercontent.com/16001446/62516149-e2dc8a80-b841-11e9-9f27-c5abc224494a.png)
I try to clear the cache explicitly using **gc.collect** but the model still continues to grow in size.
It will be great if you can help regarding this.

**Comment by petteriTeikari** [comment]
I am getting the same `RuntimeError: CUDA out of memory` with various `batch_size` reductions like @Anirudh257 and commented away the `evaluation` part and it trains past the first epoch, but now I don't then now of the generalization performance

![image](https://user-images.githubusercontent.com/1060514/62565303-6ddb7600-b87e-11e9-9191-1b03a0adcb58.png)

**Comment by Anirudh257** [comment]
@petteriTeikari I did the same too but I am only able to train the first epoch.

**Comment by Anirudh257** [comment]
These are my hyperparameters:
1) Number of training samples: 63026
2) Number of evaluation samples: 50922
3) weight_decay: 0.0001
4) base_lr: 0.1
5) step: [30, 40]
6) device: [0, 1 ]
7) batch_size: 64
8) test_batch_size: 64
9) num_epoch: 50
10) nesterov: True
11) optimizer: SGD

**Comment by lshiwjx** [comment]
The code is for pytorch0.3. What's your PyTorch version? @Anirudh257 @petteriTeikari

**Comment by Anirudh257** [comment]
@lshiwjx My pytorch version is 1.1.0

**Comment by lshiwjx** [comment]
@Anirudh257 That should be the problem.

**Comment by Anirudh257** [comment]
Thanks @lshiwjx . I will try that and let you know if the problem persists.

**Comment by petteriTeikari** [comment]
`1.0.1.post2` here @lshiwjx and corrected those other errors thrown at me due to version mismatch, and got the training to work by just commenting the `eval` part away @Anirudh257 

And there is no growing of memory use in that sense https://discuss.pytorch.org/t/cuda-error-out-of-memory-after-several-epochs/29094

![image](https://user-images.githubusercontent.com/1060514/62620440-3e297e00-b911-11e9-927b-9772f6562e86.png)

And since `0.4.0` you seem to have to switch off the backprop for evaluation to handle the memory? `torch.no_grad()` instead of the `self.model.eval()` at ? https://github.com/lshiwjx/2s-AGCN/blob/d4880e1cfc0822cc86beb2c9dd7463f904dd40ea/main.py#L415 

So putting the `model.eval()` inside `with torch.no_grad():` should fix the issue (will test later)
https://necromuralist.github.io/In-Too-Deep/posts/nano/pytorch/part-5-inference-and-validation/

**See also**

_Out of memory error during evaluation but training works fine!_
https://discuss.pytorch.org/t/out-of-memory-error-during-evaluation-but-training-works-fine/12274

_‘model.eval()’ vs ‘with torch.no_grad()’_
https://discuss.pytorch.org/t/model-eval-vs-with-torch-no-grad/19615/28

**Comment by Anirudh257** [comment]
Thanks @petteriTeikari for the detailed instructions. I will follow these and let you know if I get stuck again.

**Comment by petteriTeikari** [comment]
Yes at least for me, the repo now works @Anirudh257 in PyTorch 1.xx , and the score writing was annoyingly also set to `False` [main.py#L52](https://github.com/lshiwjx/2s-AGCN/blob/d4880e1cfc0822cc86beb2c9dd7463f904dd40ea/main.py#L52) by default so had to run some more to get some scores out for the ensemble function

**Comment by Viozer** [comment]
> These are my hyperparameters:
> 
> 1. Number of training samples: 63026
> 2. Number of evaluation samples: 50922
> 3. weight_decay: 0.0001
> 4. base_lr: 0.1
> 5. step: [30, 40]
> 6. device: [0, 1 ]
> 7. batch_size: 64
> 8. test_batch_size: 64
> 9. num_epoch: 50
> 10. nesterov: True
> 11. optimizer: SGD

Hi, I'm trying to reproduce the experiment result on NTU-RGB+D dataset. But I'm getting RuntimeError: CUDA out of memory in the feed forward process with batch_size=64. So can you tell me the amount of memory you have to use during training with batch_size=64?

**Comment by Anirudh257** [comment]
Thanks, @petteriTeikari I finally got the time and got the code running. I had to replace **volatile = True** with **with torch.no_grad()** and it worked :)

**Comment by dangao250** [comment]
> Thanks, @petteriTeikari I finally got the time and got the code running. I had to replace **volatile = True** with **with torch.no_grad()** and it worked :)



> Thanks, @petteriTeikari I finally got the time and got the code running. I had to replace **volatile = True** with **with torch.no_grad()** and it worked :)

How did you solve it? Can you tell me more about it? I'm also pytorch 1.2.0

**Comment by Anirudh257** [comment]
@dangao250 Just follow the steps that I mentioned. Replace **volatile = True** with **with torch.no_grad()**

**Comment by dangao250** [comment]
I did, but it's not working. Can you send this code out and show it to me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月16日(星期六) 晚上11:10
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




@dangao250 Just follow the steps that I mentioned. Replace volatile = True with with torch.no_grad()

**Comment by Anirudh257** [comment]
https://pastebin.com/4XQSpTVB is my code  @dangao250

**Comment by dangao250** [comment]
Have you ever done any attitude prediction on asgcn? For example, the actionable-structural Graph Convolutional Networks for skeleton-based Action Recognition


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 下午5:55
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




https://pastebin.com/4XQSpTVB is my code  @dangao250

**Comment by dangao250** [comment]
Have you ever done any attitude prediction on asgcn? For example, the actionable-structural Graph Convolutional Networks for skeleton-based Action Recognition




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 下午5:55
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




https://pastebin.com/4XQSpTVB is my code  @dangao250

**Comment by Anirudh257** [comment]
@dangao250 No, I haven't

**Comment by dangao250** [comment]
Have you ever thought about reproducing this model? I found that you like to do identification. Do you think that I sent the paper, does the prediction in him make sense?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月17日(星期天) 晚上7:55
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




@dangao250 No, I haven't

**Comment by Anirudh257** [comment]
I have used AS-GCN for normal skeleton action recognition but haven't tried identification.

**Comment by dangao250** [comment]
Do you have the accuracy of top1 and top5 in this test?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 凌晨0:36
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I have used AS-GCN for normal skeleton action recognition but haven't tried identification.

**Comment by Anirudh257** [comment]
I tried it on NTU-120.

**Comment by dangao250** [comment]
What is the accuracy rate?&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午2:22
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I tried it on NTU-120.

**Comment by dangao250** [comment]
Are you talking about the structure catalog of ntu-rgbd120?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午2:22
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I tried it on NTU-120.

**Comment by Anirudh257** [comment]
I  was getting around 75% on top1

**Comment by dangao250** [comment]
Did you reproduce the nturgbd 120 at 2sagcn?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 凌晨0:36
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I have used AS-GCN for normal skeleton action recognition but haven't tried identification.

**Comment by dangao250** [comment]
Can you show me how you reproduce the code? I refer to it.&nbsp;Accuracy is OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午3:45
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I  was getting around 75% on top1

**Comment by dangao250** [comment]
I want to see if you can reproduce the code of nturgbd120? About 2sagcn



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午3:45
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I  was getting around 75% on top1

**Comment by dangao250** [comment]
Can you show me the code you reproduced? About nturgbd120




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午2:22
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I tried it on NTU-120.

**Comment by dangao250** [comment]
Can you show me the code you reproduced? About nturgbd120




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午3:45
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I  was getting around 75% on top1

**Comment by Anirudh257** [comment]
In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
It’s getting higher and higher. Master, you are so powerful. I really ask for this part of the code. I want to intensively master the idea.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:13
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by Anirudh257** [comment]
Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
Can the part of the code generated by the data be shown to me?&nbsp;&nbsp;There are two questions, so I want to see the rookie is very embarrassed to ask too much. Sorry.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:35
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
I am sorry to affect your information so early. The rookie hopes that the mood is not bad.&nbsp; &nbsp;Config ntu120 and the place to generate ntu data, please give me a reference. Thank you, Niu Ren




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:35
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
Have a good night's sleep, come back to you during the day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:35
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
Is there a small setting? I want to give the generated data code as a reference.&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:35
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
How is your config set up? Can you look at it? And I feel that the difference between 60 and 120 is a bit obvious. What do you think?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:35
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




Actually, my code was run on NTU-120. I used this code: https://pastebin.com/4XQSpTVB for main.py. Rest are all same.

**Comment by dangao250** [comment]
Have you found out that the steps in data preprocessing seem to be two steps: alignment of the same human skeleton and skeletal energy based filtering based on the skeleton identifier.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:13
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
Have you found that there are two steps in data preprocessing here? This code is not reflected?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上8:13
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
Ntu120 here how to assign training sets and test sets, it seems that I did not see the settings, how to get rid of


就这里改60改120就可以了吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上8:13
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
ntu 120 的config 可以给我吗
&nbsp;
Can I have the CONFIG FOR NTU 120






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:13
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
Hello can you send me your email? Have you run DGNN? I would like to ask you a few questions. What do the two labels in the output mean? Why is the output data a matrix with 3 rows and 2 columns? What does it mean?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上8:13
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.

**Comment by dangao250** [comment]
73/5000

&nbsp;
Do you understand this part of the code 2sagcn, can you explain it to me, and can you give me your Eamil


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午3:45
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




I  was getting around 75% on top1

**Comment by dangao250** [comment]
73/5000

&nbsp;
Do you understand this part of the code 2sagcn, can you explain it to me, and can you give me your Eamil






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anirudh Thatipelli"<notifications@github.com&gt;; 
发送时间: 2019年11月17日(星期天) 晚上7:55
收件人: "lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;; 
抄送: "&amp;#x1F601;"<1337932153@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)




@dangao250 No, I haven't

**Comment by dangao250** [comment]
Can you show me the fusion code, still don't understand this operation&nbsp;
------------------ 原始邮件 ------------------
发件人:&nbsp;"Anirudh Thatipelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上8:13
收件人:&nbsp;"lshiwjx/2s-AGCN"<2s-AGCN@noreply.github.com&gt;;
抄送:&nbsp;"😁"<1337932153@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lshiwjx/2s-AGCN] Memory overloading issue (#12)

Can you show me the fusion code, still don't understand this operation
The accuracy rate is also very low, I hope the boss will help


In 2s-AGCN, I am using the sam code that I had sent to you earlier. I get around 80% accuracy.
