### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by NguyenDangBinh** [lshiwjx/2s-AGCN#14]
dear,
Can anyone give me the trained model because my pc is weak, no gpu?
Thannk you so much!

**Comment by lshiwjx** [comment]
It has already been released.

**Comment by erinchen824** [comment]
Could you please update the link to the pretrained model? Since I cannot find it anywhere. Thanks

**Comment by erinchen824** [comment]
> Could you please update the link to the pretrained model? Since I cannot find it anywhere. Thanks

I found it, just in the right side of the main page.
https://github.com/lshiwjx/2s-AGCN/releases/tag/v0.0
