### ISSUE TITLE
Update Pytorch

### ISSUE THREAD

**Issue by NguyenDangBinh** [lshiwjx/2s-AGCN#15]
dear,
Can you update pytorch to 1.0?
I can not install pytorch=0.3 cuda101.

**Comment by Lyndsey-Xing** [comment]
hi,

I hope the author update pytorch too~

For your problem, I try "pytorch=0.3 cuda75", it's ok.
My cuda is cuda80, the code can run,  but it will have warning.

**Comment by lshiwjx** [comment]
I will try to update it in the future. 
It should not be difficult but I really have no time now ......
Welcome for the contribution.

**Comment by Anirudh257** [comment]
@NguyenDangBinh The code runs with Pytorch 1.0 too with some minor modifications. You can check out https://github.com/lshiwjx/2s-AGCN/issues/12 for the required changes.

**Comment by dangao250** [comment]
> @NguyenDangBinh The code runs with Pytorch 1.0 too with some minor modifications. You can check out #12 for the required changes.



> @NguyenDangBinh The code runs with Pytorch 1.0 too with some minor modifications. You can check out #12 for the required changes.

After reading and interpreting pytorch 1.2, I don't understand how you can change it. Can you post the steps.

**Comment by dangao250** [comment]
> > @NguyenDangBinh The code runs with Pytorch 1.0 too with some minor modifications. You can check out #12 for the required changes.
> 
> > @NguyenDangBinh The code runs with Pytorch 1.0 too with some minor modifications. You can check out #12 for the required changes.
> 
> After reading and interpreting pytorch 1.2, I don't understand how you can change it. Can you post the steps.
I can't understand your steps

**Comment by dangao250** [comment]
> dear,
> Can you update pytorch to 1.0?
> I can not install pytorch=0.3 cuda101.

Can you tell me what to do if you solve it?
