### ISSUE TITLE
I got some wrong when I was training the net 

### ISSUE THREAD

**Issue by Dongjiuqing** [lshiwjx/2s-AGCN#16]
首先我是得到了下面这个error，
![1](https://user-images.githubusercontent.com/43560407/63692707-dea1fc80-c844-11e9-8711-7bd7d41c8ddc.jpg)

注释掉该参数后，got another error

I got this error ,but I don't know how to solve. Could you give me some advice?

Traceback (most recent call last):
  File "/home/sues/Desktop/2s-AGCN-master/main.py", line 550, in <module>
    processor.start()
  File "/home/sues/Desktop/2s-AGCN-master/main.py", line 491, in start
    self.train(epoch, save_model=save_model)
  File "/home/sues/Desktop/2s-AGCN-master/main.py", line 372, in train
    loss.backward()
  File "/home/sues/anaconda3/envs/2sAGCN/lib/python3.5/site-pac[kages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/sues/anaconda3/envs/2sAGCN/lib/python3.5/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:26
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes
![2](https://user-images.githubusercontent.com/43560407/63692729-e9f52800-c844-11e9-8596-3344e36c33af.jpg)

**Comment by lshiwjx** [comment]
First, you should check your pytorch version, it should be 0.3.
Then you can check whether the number of classes is right.

**Comment by Dongjiuqing** [comment]
Thank you ，I solved my problems. I got Error because number of classes is wrong。thank youso much

发自我的iPhone


------------------ Original ------------------

**Comment by lshiwjx** [comment]
You are welcome

**Comment by zhenyouwei** [comment]
> Thank you ，I solved my problems. I got Error because number of classes is wrong。thank youso much 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: LShi <notifications@github.com&gt; Date: Thu,Aug 29,2019 5:18 PM To: lshiwjx/2s-AGCN <2s-AGCN@noreply.github.com&gt; Cc: Dongjiuqing <657627574@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [lshiwjx/2s-AGCN] I got some wrong when I was training the net (#16) First, you should check your pytorch version, it should be 0.3. Then you can check whether the number of classes is right. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hi，could you please tell me what is the right number of classes  ？I got the same problem，I have checked the train_joint.yaml the number of num_class is 60

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1 ,2, 3]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True

**Comment by Just-A-Peek** [comment]
> > Thank you ，I solved my problems. I got Error because number of classes is wrong。thank youso much 发自我的iPhone
> > […](#)
> > ------------------ Original ------------------ From: LShi <[notifications@github.com](mailto:notifications@github.com)> Date: Thu,Aug 29,2019 5:18 PM To: lshiwjx/2s-AGCN <[2s-AGCN@noreply.github.com](mailto:2s-AGCN@noreply.github.com)> Cc: Dongjiuqing <[657627574@qq.com](mailto:657627574@qq.com)>, Author <[author@noreply.github.com](mailto:author@noreply.github.com)> Subject: Re: [lshiwjx/2s-AGCN] I got some wrong when I was training the net (#16) First, you should check your pytorch version, it should be 0.3. Then you can check whether the number of classes is right. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Hi，could you please tell me what is the right number of classes ？I got the same problem，I have checked the train_joint.yaml the number of num_class is 60
> # model
> 
> model: model.agcn.Model
> model_args:
> num_class: 60
> num_point: 25
> num_person: 2
> graph: graph.ntu_rgb_d.Graph
> graph_args:
> labeling_mode: 'spatial'
> 
> #optim
> weight_decay: 0.0001
> base_lr: 0.1
> step: [30, 40]
> # training
> 
> device: [0, 1 ,2, 3]
> batch_size: 64
> test_batch_size: 64
> num_epoch: 50
> nesterov: True

I also got the same problem,have you resolved it? If you done correctly, could you please tell me how to deal with this problem? Thank you!

**Comment by lemonci** [comment]
Hi there, also got the same error and same parameters(num_class: 60 for nutrgb+d). Could anyone help? Thanks.

@Dongjiuqing @lshiwjx 
@zhenyouwei @Just-A-Peek @541968679

**Comment by Dongjiuqing** [comment]
please double check your dataset is correct.
There are two datasets on NTU dataset but you just need the first.&nbsp;
You can try to set the NUM-CLASS=120 &nbsp;If you don’t get any errors, you should check you datasets.





发自我的iPhone


------------------ Original ------------------

**Comment by lemonci** [comment]
> 
> please double check your dataset is correct. There are two datasets on NTU dataset but you just need the first.&nbsp; You can try to set the NUM-CLASS=120 &nbsp;If you don’t get any errors, you should check you datasets. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: lemonci <notifications@github.com&gt; Date: Thu,Feb 20,2020 3:17 AM To: lshiwjx/2s-AGCN <2s-AGCN@noreply.github.com&gt; Cc: Dongjiuqing <657627574@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [lshiwjx/2s-AGCN] I got some wrong when I was training the net (#16) Hi there, also got the same error and same parameters(num_class: 60 for nutrgb+d). Could anyone help? Thanks. @Dongjiuqing @lshiwjx @zhenyouwei @Just-A-Peek @541968679 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks. It solves my problem.

**Comment by qiexing** [comment]
@Dongjiuqing Thanks, It also solves my problem. Why we need to set num_class  as 120？ Does this mean that we train the model on NTU V2 dataset？Then how can I compare with the reported accuracy on the 2s-AGCN paper?

**Comment by Dongjiuqing** [comment]
Because I guess you make a mistake for the dataset. Maybe you download the NTU RGBD 120 datasets. It’s a extended version based on NTU



发自我的&nbsp;iPad


------------------ Original ------------------
