### ISSUE TITLE
RuntimeError: running_mean should contain 126 elements not 63 (example).

### ISSUE THREAD

**Issue by JasOlean** [lshiwjx/2s-AGCN#19]
What is your elements for number of joints (18)?
When I run your code, I got this error " RuntimeError: running_mean should contain 126 elements not 63". 63 means I change number of node. 
How to adjust these elements and how to get your elements 126 for your experiment?

**Comment by lshiwjx** [comment]
The number of elements for running_mean = num_person * in_channels * num_point

**Comment by JasOlean** [comment]
When I run your kinetics data, I changed num_person = 1, in_channels = 3, num_point = 18. running_mean value is 54. In that case, I got this error "RuntimeError: running_mean should contain 108 elements not 54".
What has happened? why they said should contain 108 elements when num_person = 1?

**Comment by lshiwjx** [comment]
It should be 54, maybe the param num_person is not successfully passed to the model. 
You can try to check the data shape.
