### ISSUE TITLE
The problems of data pre-processing

### ISSUE THREAD

**Issue by liangchengwu** [lshiwjx/2s-AGCN#20]
Dear Colleagues,

For Data Preparation,  when  I  tried to run the code "python data_gen/ntu_gendata.py", the code run the file of “preprocess.py”,   and run the function "pre_normalization(data, zaxis=[0, 1], xaxis=[8, 4]):"  

It has encountered the following problems:

pad the null frames with the previous frames
  0%|          | 0/40091 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "ntu_gendata.py", line 166, in <module>
    part=p)
  File "ntu_gendata.py", line 140, in gendata
    fp = pre_normalization(fp)
  File "../data_gen/preprocess.py", line 30, in pre_normalization
    s[i_s, i_p, i_f:] = pad
ValueError: could not broadcast input array from shape (186,25,3) into shape (238,25,3)

What is the reason?
And how to fix it?

Thanks
LCW

**Comment by Anirudh257** [comment]
@liangchengwu Some files are corrupted and don't work. You can try to print the name of the corrupted file when the exception occurs and remove them.
