### ISSUE TITLE
What does the “centralization” operation mean in the generating process of kinetics dataset？

### ISSUE THREAD

**Issue by menggr1231** [lshiwjx/2s-AGCN#21]
# centralization
data_numpy[0:2] = data_numpy[0:2] - 0.5
data_numpy[1:2] = -data_numpy[1:2]
data_numpy[0][data_numpy[2] == 0] = 0
data_numpy[1][data_numpy[2] == 0] = 0

What does the “centralization” operation mean in the generating process of kinetics dataset？Especially the first two operations.

**Comment by lshiwjx** [comment]
The data in kinetics ranges from 0 to 1, "-0.5" makes it to -0.5-0.5. 
The second row is the direction problem, for better visualization.
