### ISSUE TITLE
problem with gen_bone_data.py

### ISSUE THREAD

**Issue by JaxferZ** [lshiwjx/2s-AGCN#22]
你好，请问一下我跑gen_bone_data.py时报错，好像是矩阵的维度有问题，该怎么解决，谢谢
lin@lin:~/2s-AGCN-master/data_gen$ python gen_bone_data.py 
ntu/xsub train
  4%|█▋                                       | 1/25 [06:49<2:43:40, 409.20s/it]Traceback (most recent call last):
  File "gen_bone_data.py", line 50, in <module>
    fp_sp[:, :, :, v1, :] = data[:, :, :, v1, :] - data[:, :, :, v2, :]
IndexError: index 20 is out of bounds for axis 3 with size 18
  4%|█▋                                       | 1/25 [06:49<2:43:45, 409.41s/it]

**Comment by lshiwjx** [comment]
你应该是换了数据吧，改下关键点的数量

**Comment by JaxferZ** [comment]
好的，谢谢，我重新跑了一下preprocess就解决了，但是现在到了
python main.py --config ./config/nturgbd-cross-view/train_joint.yaml的时候一直显示CUDA OUT OF MEMORY
z = self.conv_d[i](torch.matmul(A2, A1).view(N, C, T, V))
RuntimeError: CUDA out of memory. Tried to allocate 236.00 MiB (GPU 0; 10.76 GiB total capacity; 9.47 GiB already allocated; 84.31 MiB free; 132.66 MiB cached)

**Comment by RayLeijingsi** [comment]
> 好的，谢谢，我重新跑了一下preprocess就解决了，但是现在到了
> python main.py --config ./config/nturgbd-cross-view/train_joint.yaml的时候一直显示CUDA OUT OF MEMORY
> z = self.conv_d[i](torch.matmul(A2, A1).view(N, C, T, V))
> RuntimeError: CUDA out of memory. Tried to allocate 236.00 MiB (GPU 0; 10.76 GiB total capacity; 9.47 GiB already allocated; 84.31 MiB free; 132.66 MiB cached)

batch_size改小

**Comment by czhaneva** [comment]
请问下yaml文件中的train_data_joint.npy以及其他的joint.npy是不是都是通过ntu_gendata.py生成的？
然后bone.npy是不是需要额外运行gen_bone_data.py文件来处理上面提取出来的joint.npy数据？求解答，感谢

**Comment by lshiwjx** [comment]
> 请问下yaml文件中的train_data_joint.npy以及其他的joint.npy是不是都是通过ntu_gendata.py生成的？
> 然后bone.npy是不是需要额外运行gen_bone_data.py文件来处理上面提取出来的joint.npy数据？求解答，感谢

是的
