### ISSUE TITLE
Training log of 2sAGCN for NTU-RGB cross subject

### ISSUE THREAD

**Issue by thancaocuong** [lshiwjx/2s-AGCN#27]
Hi, thank you for your awsome emplementation. Can you release training log of 2sAGCN for NTU-RGB cross subject. thank you.

**Comment by lshiwjx** [comment]
Top1: 85.26% for joint data and Top1: 86.24% for bone data.

**Comment by thancaocuong** [comment]
thank you, it's good when compare to STGCN

**Comment by thancaocuong** [comment]
thank you, it's good when compare to STGCN
