### ISSUE TITLE
请问论文中的图8，图9是怎么画的？

### ISSUE THREAD

**Issue by desertfex** [lshiwjx/2s-AGCN#30]
图8，图9画出了骨架，并用大小圈代表了关节点连接的strength，感觉看上去特别直观。我从您github公开的代码中没看到相关画图的代码，所以向您请教一下，您是怎么画出来的？有没有可以分享的代码呢？如能不吝赐教，将不胜感激！谢谢！

**Comment by lshiwjx** [comment]
Here is an example function. But it is not the same as before.

`def draw_skeleton2(ax, joints, title='', axis=False, connect=None, additional_connect=None, zlimb=[0, 1], label=""):
    colors = ['dodgerblue', 'steelblue', 'darkorange']
    '''
    # param: joints[v, c]
    '''
    ax.imshow(np.ones((224, 224, 3), dtype=np.uint8) * 255)
    joints *= 224
    # plot joint
    for num, joint in enumerate(joints):
        ax.scatter(joint[0], joint[1], color=colors[0])

    # plot additional edges
    if additional_connect is not None:
        for connection in additional_connect:
            t = connection[0]
            f = connection[1]
            s = connection[2]
            ax.plot([joints[f][0], joints[t][0]], [joints[f][1], joints[t][1]], color=colors[2], alpha=s, linewidth=1)

    # plot edge
    if connect is not None:
        for connection in connect:
            t = connection[0]
            f = connection[1]
            ax.plot([joints[f][0], joints[t][0]], [joints[f][1], joints[t][1]], color=colors[1], linewidth=1)
    ax.tick_params(axis='both', which='both', bottom='off', top='off', labelbottom='off', right='off',
                   left='off', labelleft='off')`

**Comment by desertfex** [comment]
Thank you very much!
But how to use this funtion? What're the joints, connect and additional_connect stand for?
