### ISSUE TITLE
What's the point of adding y = none to the agcn.py file

### ISSUE THREAD

**Issue by dutlzn** [lshiwjx/2s-AGCN#31]
**y = None**
        for i in range(self.num_subset):
            A1 = self.conv_a[i](x).permute(0, 3, 1, 2).contiguous().view(N, V, self.inter_c * T)
            A2 = self.conv_b[i](x).view(N, self.inter_c * T, V)
            A1 = self.soft(torch.matmul(A1, A2) / A1.size(-1))  # N V V
            A1 = A1 + A[i]
            A2 = x.view(N, C * T, V)
            z = self.conv_d[i](torch.matmul(A2, A1).view(N, C, T, V))
            y = z + y if y is not None else z

**Comment by dutlzn** [comment]
这个y有什么意义吗

**Comment by desertfex** [comment]
这是个for循环啊，第一次y = none，第二次y = z，每循环一次，y就会加上新算出来的z，更新一次
