### ISSUE TITLE
dataload error

### ISSUE THREAD

**Issue by xuanshibin** [lshiwjx/2s-AGCN#43]
thank your source code, but when I run this code, The following error occurs:
ValueError: num_samples should be a positive integer value, but got num_samples=0

I've run the program 'python data_gen/ntu_gendata.py 'before, and some documents were generated :
train_data_joint.npy
train_label.pkl
val_data_joint.npy
val_label.pkl

but their size are all 1K

How should I deal with, trouble you give directions.

thanks

**Comment by xuanshibin** [comment]
The problem has been solved

**Comment by cryyin** [comment]
how did you solve it? I have the same problem

**Comment by cryyin** [comment]
solved it, I unzip data with a wrong path....
