### ISSUE TITLE
No module named 'data_gen'  and  No such file or directory: '../data/kinetics_raw/kinetics_val'

### ISSUE THREAD

**Issue by XiongXintyw** [lshiwjx/2s-AGCN#49]
When I run "python data_gen/ntu_gendata.py", gets the error : ModuleNotFoundError: No module named 'data_gen'.

When I run "python data_gen/kinetics_gendata.py", gets the error : FileNotFoundError: [Errno 2] No such file or directory: '../data/kinetics_raw/kinetics_val'.

My raw data has put in the ./data.

Needs your help！

**Comment by Lyndsey-Xing** [comment]
check your file name

**Comment by Delia16** [comment]
When I run "python data_gen/ntu_gendata.py", gets the error : ModuleNotFoundError: No module named 'data_gen'.

**Comment by siehlema** [comment]
You need to run the python script from within the data_gen folder. E.g.:
cd data_gen
python ntu_gendata.py
