### ISSUE TITLE
请问什么时候会release预训练好的模型呢？

### ISSUE THREAD

**Issue by jin-miao-cai** [lshiwjx/2s-AGCN#5]
您好，非常感谢您的对这份工作的开源。
如题，在测试的时候，我发现没有与训练的模型，因此需要自己重新训练。
所以想问一下，什么时候会release预训练好的模型呢？
再次感谢！

**Comment by lshiwjx** [comment]
之后可能会，但暂时还没有计划，我需要和老板讨论一下。
