### ISSUE TITLE
运行python data_gen/ntu_gendata.py指令时报错 No module named 'data_gen'

### ISSUE THREAD

**Issue by Delia16** [lshiwjx/2s-AGCN#53]
运行python data_gen/ntu_gendata.py指令时报错 No module named 'data_gen'

![image](https://user-images.githubusercontent.com/52527705/79976155-bef3ce80-84ce-11ea-92a6-39ecf0448938.png)

**Comment by fylql** [comment]
我也有这个问题 请问是怎么解决的呢
