### ISSUE TITLE
augmentation in feeder

### ISSUE THREAD

**Issue by Solaire-V** [lshiwjx/2s-AGCN#6]
Hi,
I want to know the data augmentation in the feeder has not improved? Does the length of the input have a big influence?
Also, have you trained the model on the 120 dataset? How's the accuracy?

**Comment by lshiwjx** [comment]
I have tried the augmentation but found no improvement for NTU-RGBD. For Skeleton-Kinetics it is important. 
The influence of the input length is not investigated. 
I haven't tried the 120 dataset.

**Comment by Solaire-V** [comment]
I tried to change the input length to 64. For joint stream, I got 94.59 top1 acc. And for bone stream, I got 94.11 top1 acc. The final fusion result is 95.53.

**Comment by Lixmdeep** [comment]
> I tried to change the input length to 64. For joint stream, I got 94.59 top1 acc. And for bone stream, I got 94.11 top1 acc. The final fusion result is 95.53.

Divide the input sequence into 64 equal segments, and then choose a random frame from each segment?@VSunN

**Comment by Lixmdeep** [comment]
@VSunN

**Comment by Solaire-V** [comment]
@Lixmdeep , I just changed the window size in the configuration to 64.

**Comment by hongge831** [comment]
@VSunN I can not reproduce your result, can you tell me any other configurations you have changed in the codefile?  thanks alot.

**Comment by Solaire-V** [comment]
@hongge831 set random_choose=True and window_size=64 in config/nturgbd-cross-view/train_joint.yaml

**Comment by erinchen824** [comment]
> @hongge831 set random_choose=True and window_size=64 in config/nturgbd-cross-view/train_joint.yaml

The paper only mentioned to set T to 300 without any other augmentation, whether using random choose be a kind of augmentation? Can I set it to be True to reproduce the results? Thx!
