### ISSUE TITLE
The ‘num_class’ in the config file of ntu data is 60, shouldn't it be 120?

### ISSUE THREAD

**Issue by wkxurn** [lshiwjx/2s-AGCN#61]
In the ntu data, the action categories for training and testing are both 120. Why is ’num_class‘ set to 60 in the config file? 
When num_class=60, the training program will report an error when label>60.
I get the following error:
`block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.`

 I change it to 120 and it will not go wrong.
But I don’t know the reason why the parameter is set to 60.This will cause me to load the pre-trained model provided by the author. 
I get the following error:
```
RuntimeError: Error(s) in loading state_dict for Model:
Missing key(s) in state_dict: "l1.gcn1.PA", "l1.gcn1.conv_a.0.weight", "l1.gcn1.conv_a.0.bias", "l1.gcn1.conv_a.1.weight", "l1.gcn1.conv_a.1.bias",...................
```

Do someone know the reason? Thank you

**Comment by AndreaRoss96** [comment]
Did you solve this problem?
