### ISSUE TITLE
用released model做test的时候提示 Unexpected key(s) in state_dict:

### ISSUE THREAD

**Issue by tailin1009** [lshiwjx/2s-AGCN#67]
`python main.py --config ./config/nturgbd-cross-view/test_joint.yaml` 这段代码能得到论文的结果。
但是到了这段 `python main.py --config ./config/nturgbd-cross-view/test_bone.yaml``，会提示`RuntimeError: Error(s) in loading state_dict for Model:`
        

Unexpected key(s) in state_dict: "l1.gcn1.conv_res.0.weight", "l1.gcn1.conv_res.0.bias", "l1.gcn1.conv_res.1.weigh
t", "l1.gcn1.conv_res.1.bias", "l1.gcn1.conv_res.1.running_mean", "l1.gcn1.conv_res.1.running_var", "l5.gcn1.conv_res.0.we
ight", "l5.gcn1.conv_res.0.bias", "l5.gcn1.conv_res.1.weight", "l5.gcn1.conv_res.1.bias", "l5.gcn1.conv_res.1.running_mean
", "l5.gcn1.conv_res.1.running_var", "l8.gcn1.conv_res.0.weight", "l8.gcn1.conv_res.0.bias", "l8.gcn1.conv_res.1.weight",
"l8.gcn1.conv_res.1.bias", "l8.gcn1.conv_res.1.running_mean", "l8.gcn1.conv_res.1.running_var".

看起来是这个pretrained模型与提供的代码不匹配，我怎么做才能得到结果呢！
期待回复！

**Comment by erinchen824** [comment]
Hi, where can I download the pretrained model? Thanks!

**Comment by tailin1009** [comment]
> Hi, where can I download the pretrained model? Thanks!
https://github.com/lshiwjx/2s-AGCN/releases
On the  right side of the main page.
Cheers

**Comment by tailin1009** [comment]
Thanks!
I have retrained this model and got the results.
