### ISSUE TITLE
关于训练时日志打印的问题

### ISSUE THREAD

**Issue by XieLinMofromsomewhere** [lshiwjx/2s-AGCN#74]
为什么训练打印日志的时候，Training Epoch的进度条一下子就结束了，而Eval Epoch的进度条正常进行，似乎是没有进行训练

![1111](https://user-images.githubusercontent.com/40623822/101734142-d08bf400-3afa-11eb-8ef2-184f60cd8a1e.png)

**Comment by Frank-Lin-57** [comment]
请问，您是否有重现出结果？

**Comment by XieLinMofromsomewhere** [comment]
> 请问，您是否有重现出结果？

目前没有，但是STGCN我重现了结果

**Comment by Frank-Lin-57** [comment]
> > 请问，您是否有重现出结果？
> 
> 目前没有，但是STGCN我重现了结果

谢谢回复，请问你使用的设备大概是什么配置？

**Comment by XieLinMofromsomewhere** [comment]
> > > 请问，您是否有重现出结果？
> > 
> > 
> > 目前没有，但是STGCN我重现了结果
> 
> 谢谢回复，请问你使用的设备大概是什么配置？

2块 1080ti ，也许显存大的更好

**Comment by youyuanrsq** [comment]
> > 请问，您是否有重现出结果？
> 
> 目前没有，但是STGCN我重现了结果

请问您是用aagcn的代码重现STGCN的结果吗？我在打算重现A-STGCN时报错没有定义self.mask这个变量，不知道是什么原因、。。。
