### ISSUE TITLE
what is (N, C, T, V, M) in agcn.py? 

### ISSUE THREAD

**Issue by lodado** [lshiwjx/2s-AGCN#76]
thank you for sharing code and information :) 
I have some question about agcn.py code
1. what is (N, C, T, V, M) in agcn.py? 
i guess 
T is 300 frame, 
V is the similarity between nodes, 
M is number of men in one video,
but i am not sure that it is right

2.  are bone train code and joint train(agcn.py) code same?
if it is not, is bone train code aagcn.py?

**Comment by erinchen824** [comment]
> thank you for sharing code and information :)
> I have some question about agcn.py code
> 
> 1. what is (N, C, T, V, M) in agcn.py?
>    i guess
>    T is 300 frame,
>    V is the similarity between nodes,
>    M is number of men in one video,
>    but i am not sure that it is right
> 2. are bone train code and joint train(agcn.py) code same?
>    if it is not, is bone train code aagcn.py?

1. the meaning of (N, C, T, V, M) 
N is the batch size of video
T is the number of frames in each video
V is the number of nodes in a skeleton, which is 25 for NTU dataset
M is number of person in one video, which is 2 for NTU dataset

2. According to the config files, the train code for joint and bone is same. As for the aagcn.py, it has attention mechanism in it compared to agcn.py. They are two different model.

**Comment by lodado** [comment]
C is channel(3), right?
thank you for your reply
